//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow_Insurance_Agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInsurrancePayment
    {
        public System.Guid ID { get; set; }
        public System.Guid CarInsurancePolicyID { get; set; }
        public decimal Amount { get; set; }
        public string Method { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> BankID { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string Check_No { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Check_Name { get; set; }
    }
}
